sudo: false
dist: trusty

notifications:
  email: false

language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'

cache: pip

install:
  - sudo apt-get install ghostscript
  - pip install tox

script:
  - python setup.py build
  - tox
